# (PART\*) Quyển Thượng {-}

# Thần thông trên cung trời Đao Lợi  {#than-thong-tren-cung-troi-dao-loi}
  
## Phật hiện thần thông  {- #phat-hien-than-thong}
  
Ta nghe như thế này: Một thuở nọ, tại cung trời Đao Lợi, Đức Phật vì Thánh mẫu mà thuyết pháp:  
  
Lúc đó, bất khả thuyết bất khả thuyết tất cả chư Phật và đại Bồ Tát trong vô lượng thế giới ở mười phương đều đến hội họp, rồi đồng khen ngợi rằng:  
  
Đức Phật Thích Ca Mâu Ni có thể ở trong đời ác ngũ trược mà hiện sức "đại trí huệ thần thông chẳng thể nghĩ bàn" đề điều phục chúng sanh cang cường làm cho chúng nó rõ "pháp khổ pháp vui".  
  
Khen xong, chư Phật đều sai thị giả kính thăm Đức Thế Tôn.  
  
Bấy giờ, Đức Như Lai mỉm cười phóng ra trăm nghìn vừng mây sáng rõ lớn. Như là: vừng mây sáng rỡ đầy đủ, vừng mây sáng rỡ đại từ bi, vừng mây sáng rỡ đại trí huệ, vừng mây sáng rỡ đại Bát nhã, vừng mây sáng rỡ đại Tam muội, vừng mây sáng rỡ đại kiết tường, vừng mây sáng rỡ đại phước đức, vừng mây sáng rỡ đại công đức, vừng mây sáng rỡ đại quy y, vừng mây sáng rỡ đại tán thán... Đức Phật phóng ra bất khả thuyết vừng mây sáng sỡ như thế rồi lại phát ra các thứ tiếng vi diệu.  
  
Như là: tiếng Bố thí độ, tiếng Trì giới độ, tiếng Nhẫn nhục độ, tiếng Tinh tấn độ, tiếng Thiền định độ, tiếng Bát nhã độ, tiếng Từ bi, tiếng Hỷ xả, tiếng Giải thoát, tiếng Vô lậu, tiếng Trí huệ, tiếng Sư tử hống, tiếng Đại Sư tử hống, tiếng Mây sấm, tiếng Mây sấm lớn.  
  
## Trời, Rồng... hội họp  {- #troi-rong-hoi-hop}
  
Khi Đức Phật phát ra bất khả thuyết bất khả thuyết tiếng vi diệu như thế xong, thời có vô lượng ức hàng Trời, Rồng, Quỷ, Thần ở trong cõi Ta Bà và cõi nước phương khác cũng đến hội họp nơi cung trời Đao Lợi.  
  
Như là: Trời Tứ Thiên vương, trời Đao Lợi, trời Tu Diệm Ma, trời Đâu Suất Đà, trời Hóa Lạc, trời Tha Hóa Tự Tại, trời Phạm Chúng, trời Phạm Phụ, trời Đại Phạm, trời Thiểu Quang, trời Vô Lượng Quang, trời Quang Âm, trời Thiểu Tịnh, trời Vô Lượng Tịnh, trời Biến Tịnh, trời Phước Sanh, trời Phước Ái, trời Quảng Quả, trời Nghiêm Sức, trời Vô Lượng Nghiêm Sức, trời Nghiêm Sức Quả Thiệt, trời Vô Tưởng, trời Vô Phiền, trời Vô Nhiệt, trời Thiện Kiến, trời Thiện Hiện, trời Sắc Cứu Cánh, trời Ma Hê Thủ La, cho đến trời Phi Tưởng, Phi Phi Tưởng xứ. Tất cả Thiên chúng, Long chúng, cùng các chúng Quỷ, Thần đều đến hội họp.  
  
Lại có những vị thần ở cõi Ta Bà cùng cõi nước phương khác, như: Thần biển, Thần sông, Thần rạch, Thần cây, Thần núi, Thần đất, Thần sông chằm, Thần lúa mạ, Thần chủ ngày, Thần chủ đêm, Thần hư không, Thần trên trời, Thần chủ ăn uống, Thần cây cỏ... Các vị Thần như thế đều đến hội họp.  
  
Lại có những Đại Quỷ vương ở cõi Ta Bà cùng cõi nước phương khác, như: Ác Mục Quỷ vương, Đạm Huyết Quỷ vương, Đạm Tinh Khí Quỷ vương, Đạm Thai Noãn Quỷ vương, Hành Bịnh Quỷ vương, Nhiếp Độc Quỷ vương, Từ Tâm Quỷ vương, Phước Lợi Quỷ vương, Đại Ái Kính Quỷ vương... các Quỷ vương như thế đều đến hội họp.  
  
## Đức Phật phát khởi  {- #duc-phat-phat-khoi}
  
Bấy giờ, Đức Thích Ca Mâu Ni Phật bảo ngài Văn Thù Sư Lợi Pháp Vương tử đại Bồ Tát rằng: "Ông xem coi tất cả chư Phật, Bồ Tát và Trời, Rồng, Quỷ, Thần đó ở trong thế giới này cùng thế giới khác, ở trong quốc độ này cùng quốc độ khác, nay đều đến hội họp tại cung trời Đao Lợi như thế, ông có biết số bao nhiêu chăng?"  
  
Ngài Văn Thù Sư Lợi bạch Phật rằng: "Bạch Đức Thế Tôn! Nếu dùng thần lực của con để tính đếm trong nghìn kiếp cũng không biết là số bao nhiêu!"  
  
Đức Phật bảo ngài Văn Thù Sư Lợi rằng: "Đến Ta dùng Phật nhãn xem hãy còn không đếm xiết! Số Thánh, phàm này đều là của ngài Địa Tạng Bồ Tát từ thuở kiếp lâu xa đến nay, hoặc đã độ, hoặc đương độ, chưa độ, hoặc đã thành tựu, đang thành tựu, chưa thành tựu."  
  
Ngài Văn Thù Sư Lợi bạch Đức Phật rằng: "Từ thuở lâu xa về trước con đã tu căn lành chứng đặng trí vô ngại, nghe lời Đức Phật nói đó thời tin nhận liền. Còn hàng tiểu quả Thanh Văn, Trời, Rồng tám bộ chúng và những chúng sanh trong đời sau, dầu nghe lời thành thật của Như Lai, nhưng chắc là sanh lòng nghi ngờ, dầu cho có lạy vâng đi nữa cũng chưa khỏi hủy báng. Cúi mong Đức Thế Tôn nói rõ nhơn địa của ngài Địa Tạng Bồ Tát; Ngài tu hạnh gì, lập nguyện gì mà thành tựu được sự không thể nghĩ bàn như thế?"  
  
Đức Phật bảo ngài Văn Thù Sư Lợi rằng: "Ví như bao nhiêu cỏ, cây, lùm, rừng, lúa, mè, tre, lau, đá, núi, bụi bặm trong cõi tam thiên đại thiên, cứ một vật làm một sông Hằng, rồi cứ số cát trong mỗi sông Hằng, một hột cát làm một cõi nước, rồi trong một cõi nước cứ một hột bụi nhỏ làm một kiếp, rồi bao nhiêu số bụi nhỏ chứa trong một kiếp đều đem làm kiếp cả. Từ lúc ngài Địa Tạng Bồ Tát chứng quả vị Thập địa Bồ Tát đến nay nghìn lần lâu hơn số kiếp tỷ dụ ở trên, huống là những thuở ngài Địa Tạng Bồ Tát còn ở bậc Thanh Văn và Bích Chi Phật!"  
  
Này Văn Thù Sư Lợi! Oai thần thệ nguyện của Bồ Tát đó không thể nghĩ bàn được. Về đời sau, nếu có trang thiện nam, người tín thiện nữ nào nghe danh tự của Địa Tạng Bồ Tát, hoặc khen ngợi, hoặc chiêm ngưỡng vái lạy, hoặc xưng danh hiệu, hoặc cúng dường, nhẫn đến vẽ, khắc, đắp, sơn hình tượng của Địa Tạng Bồ Tát, thời người đó sẽ được một trăm lần sanh lên cõi trời Đao Lợi, vĩnh viễn chẳng còn bị sao đọa vào chốn ác đạo.  
  
## Trưởng giả tử phát nguyện  {- #truong-gia-phat-nguyen}
  
Này Văn Thù Sư Lợi! Trải qua bất khả thuyết bất khả thuyết kiếp lâu xa về trước, tiền thân của ngài Địa Tạng Bồ Tát làm một vị Trưởng giả tử. Lúc đó, trong đời có Đức Phật hiệu là: Sư Tử Phấn Tấn Cụ Túc Vạn Hạnh Như Lai, Trưởng giả tử thấy Đức Phật tướng mạo tốt đẹp nghìn phước trang nghiêm, mới bạch hỏi Đức Phật tu hạnh nguyện gì mà đặng tốt đẹp như thế?  
  
Khi ấy, Đức Sư Tử Phấn Tấn Cụ Túc Vạn Hạnh Như Lai bảo Trưởng giả tử rằng: "Muốn chứng được thân tướng tốt đẹp này, cần phải trải qua trong một thời gian lâu xa độ thoát tất cả chúng sanh bị khốn khổ."  
  
Này Văn Thù Sư Lợi! Trưởng giả tử nghe xong liền phát nguyện rằng: "Từ nay cho đến tột số chẳng thể kể xiết ở đời sau, tôi vì những chúng sanh tội khổ trong sáu đường giảng bày nhiều phương tiện làm cho chúng đó được giải thoát hết cả, rồi tự thân tôi mới chứng thành Phật đạo."  
  
Bởi ở trước Đức Phật Sư Tử Phấn Tấn Cụ Túc Vạn Hạnh Như Lai, Ngài lập nguyện rộng đó, nên đến nay đã trải qua trăm nghìn muôn ức vô số bất khả thuyết kiếp, mà Ngài vẫn còn làm vị Bồ Tát!  
  
## Bà La Môn nữ cứu mẹ  {- #ba-la-mon-nu-cuu-me}
  
Lại thuở bất khả tư nghị vô số kiếp về trước, lúc đó có Đức Phật hiệu là: Giác Hoa Định Tự Tại Vương Như Lai, Đức Phật ấy thọ đến bốn trăm nghìn muôn ức vô số kiếp. Trong thời Tượng pháp, có một người con gái dòng Bà La Môn, người này nhiều đời chứa phước đức sâu dày, mọi người đều kính nể, khi đi đứng, lúc nằm ngồi, chư Thiên thường theo hộ vệ. Bà mẹ của người mê tín tà đạo, thường khinh khi ngôi Tam Bảo. Thuở ấy, mặc dầu Thánh nữ đem nhiều lời phương tiện khuyên nhủ bà mẹ người, hầu làm cho bà mẹ người sanh chánh kiến, nhưng mà bà mẹ người chưa tin hẳn. Chẳng bao lâu bà ấy chết thần hồn sa đọa vào Vô Gián địa ngục.  
  
Lúc đó, Thánh nữ biết rằng người mẹ khi còn sống không tin nhân quả, liệu chắc phải theo nghiệp quấy mà sanh vào đường ác. Thánh nữ bèn bán nhà, đất, sắm nhiều hương, hoa cùng những đồ lễ cúng, rồi đem cũng dường tại các chùa tháp thờ Đức Phật Giác Hoa Định Tự Tại Vương. Trong một ngôi chùa kia thấy hình tượng của Đức Phật Giác Hoa Định Tự Tại Vương đắp vẽ oai dung đủ cách tôn nghiêm.  
  
Thánh nữ chiêm bái tượng của Đức Phật lại càng sanh lòng kính ngưỡng, tự nghĩ thầm rằng: "Đức Phật là Đấng Đại giác đủ tất cả trí huệ, nếu Đức Phật còn trụ ở đời, thì khi mẹ tôi khuất, tôi đến bạch hỏi Phật, chắc thế nào cũng rõ mẹ tôi sanh vào chốn nào."  
  
Nghĩ đến đó, Thánh nữ buồn tủi rơi lệ chăm nhìn tượng Như Lai mà lòng quyến luyến mãi.  
  
Bỗng nghe trên hư không có tiếng bảo rằng: "Thánh nữ đương khóc kia, thôi đừng có bi ai quá lắm! Nay Ta sẽ bảo cho ngươi biết chỗ của mẹ ngươi."  
  
Thánh nữ chắp tay hướng lên hư không mà vái rằng: "Đức Thần nào đó mà giải bớt lòng sầu lo của tôi như thế? Từ khi mẹ tôi mất đến nay, tôi thương nhớ ngày đêm, không biết đâu để hỏi cho rõ mẹ tôi thác sanh vào chốn nào?"  
  
Trên hư không lại có tiếng bảo Thánh nữ rằng: "Ta là Đức Phật quá khứ Giác Hoa Định Tự Tại Vương Như Lai mà người đương chiêm bái đó. Thấy ngươi thương nhớ mẹ trội hơn thường tình của chúng sanh, nên Ta đến chỉ bảo."  
  
Thánh nữ nghe nói xong, liền té xỉu xuống, tay chân mình mẩy đều bị tổn thương. Những người đứng bên vội vàng đỡ dậy, một lát sau Thánh nữ mới tỉnh lại rồi bạch cùng trên hư không rằng: "Cúi xin Đức Phật xót thương bảo ngay cho rõ chỗ thác sanh của mẹ con, nay thân tâm của con sắp chết mất!"  
  
Đức Giác Hoa Định Tự Tại Vương Như Lai bảo Thánh nữ rằng: "Cúng dường xong, ngươi mau mau trở về nhà, rồi ngồi ngay thẳng nghĩ tưởng danh hiệu của Ta, thời ngươi sẽ biết chỗ thác sanh của mẹ ngươi."  
  
Lễ Phật xong, Thánh nữ liền trở về nhà. Vì thương nhớ mẹ, nên Thánh nữ ngồi ngay thẳng niệm danh hiệu của Đức Giác Hoa Định Tự Tại Vương Như Lai trải suốt một ngày một đêm. Bỗng thấy thân mình đến một bờ biển kia. Nước trong biển đó sôi sùng sục, có rất nhiều thú dữ thân thể toàn bằng sắt, bay nhảy trên mặt biển, chạy rảo bên này, xua đuổi bên kia.  
  
Thấy những trai cùng gái số nhiều đến nghìn muôn thoạt chìm thoạt nổi ở trong biển, bị các thú dữ giành nhau ăn thịt.  
  
Lại thấy quỷ Dạ Xoa hình thù đều lạ lùng: hoặc nhiều tay, nhiều mắt, nhiều chân, nhiều đầu... răng nanh chĩa ra ngoài miệng bén nhọn dường gươm, lùa những người tội gần thú dữ. Rồi quỷ lại chụp bắt người tội, túm quắp đầu chân người tội lại, hình trạng muôn thứ chẳng dám nhìn lâu.  
  
Khi ấy, Thánh nữ nhờ nương sức niệm Phật nên tự nhiên không kinh sợ.  
  
Có một vị Quỷ vương tên là Vô Độc, đến cúi đầu nghinh tiếp, hỏi Thánh nữ rằng: "Hay thay Bồ Tát! Ngài có duyên sự gì đến chốn này?"  
  
Thánh nữ hỏi Quỷ vương rằng: "Đây là chốn nào?"  
  
Quỷ vương Vô Độc đáp rằng: "Đây là từng biển thứ nhất ở phía Tây núi đại Thiết Vi."  
  
Thánh nữ hỏi rằng: "Tôi nghe trong núi Thiết Vi có địa ngục, việc ấy có thiệt như thế chăng?"  
  
Vô Độc đáp rằng: "Thiệt có địa ngục."  
  
Thánh nữ hỏi rằng: "Nay tôi làm sao để được đến chốn địa ngục đó?"  
  
Vô Độc đáp rằng: "Nếu không phải sức oai thần cần phải do nghiệp lực. Ngoài hai điều này ra ắt không bao giờ có thể đến đó được."  
  
Thánh nữ lại hỏi: "Duyên cớ vì sao mà nước trong biển này sôi sùng sục như thế, và có những người tội cùng với các thú dữ?"  
  
Vô Độc đáp rằng: "Những người tội trong biển này là những kẻ tạo ác ở cõi Diêm Phù Đề mới chết, trong khoảng bốn mươi chín ngày không người kế tự để làm công đức hầu cứu vớt khổ nạn cho; lúc sống, kẻ đó lại không làm được nhân lành nào cả.  
  
Vì thế nên cứ theo nghiệp ác của họ đã gây tạo mà cảm lấy báo khổ ở địa ngục, tự nhiên họ phải lội qua biển này.  
  
Cách biển này mười muôn do tuần về phía Đông lại có một cái biển, những sự thống khổ trong biển gấp bội hơn biển này.  
  
Phía Đông của biển đó lại có một cái biển nữa, sự thống khổ trong đó càng trội hơn.  
  
Đó đều là do những nghiệp nhân xấu xa của ba nghiệp mà cảm vời ra, đồng gọi là biển nghiệp, chính là ba cái biển này vậy."  
  
Thánh nữ lại hỏi Quỷ vương Vô Độc rằng: "Địa ngục ở đâu?"  
  
Vô Độc đáp rằng: "Trong ba cái biển đó đều là địa ngục, nhiều đến số trăm nghìn, mỗi ngục đều khác nhau. Về địa ngục lớn thời có 18 chỗ, bực kế đó có 500 chỗ đủ không lường sự khổ sở, bực kế nữa có đến nghìn trăm cũng đầy không lường sự thống khổ."  
  
Thánh nữ lại hỏi Quỷ vương rằng: "Thân mẫu của tôi mới khuất gần đây, không rõ thần hồn của người phải sa vào chốn nào?"  
  
Quỷ vương hỏi Thánh nữ rằng: "Thân mẫu của Bồ Tát khi còn sống quen làm những nghiệp gì?"  
  
Thánh nữ đáp rằng: "Thân mẫu của tôi mê tín tà đạo khinh chê ngôi Tam Bảo, hoặc có lúc tạm thời tin Chánh pháp, xong rồi chẳng kính. Dầu khuất không bao lâu, mà chưa rõ đọa lạc vào đâu?"  
  
Vô Độc hỏi rằng: "Thân mẫu của Bồ Tát tên họ là gì?"  
  
Thánh nữ đáp rằng: "Thân phụ và thân mẫu của tôi đều dòng dõi Bà La Môn. Thân phụ tôi hiệu là Thi La Thiện Kiến. Thân mẫu tôi hiệu là Duyệt Đế Lợi."  
  
Vô Độc chắp tay thưa Thánh nữ rằng: "Xin Thánh nữ hãy trở về, chớ đem lòng thương nhớ buồn rầu quá lắm nữa. Tội nữ Duyệt Đế Lợi được sanh lên cõi trời đến nay đã ba ngày rồi.  
  
Nghe nói nhờ con gái của người có lòng hiếu thuận, vì mẹ mà sắm sửa lễ vật, tu tạo phước lành, cúng dường chùa pháp, thờ Đức Giác Hoa Định Tự Tại Vương Như Lai. Chẳng phải chỉ riêng thân mẫu của Bồ Tát đặng thoát khỏi địa ngục, mà ngày đó những tội nhơn Vô Gián cũng đều được vui vẻ, đồng đặng thác sanh cả."  
  
Nói xong Quỷ Vương chắp tay chào Thánh nữ mà cáo lui.  
  
Bấy giờ, Thánh nữ dường chiêm bao chợt tỉnh, rõ biết việc đó rồi, bèn đối trước tháp tượng của Đức Giác Hoa Định Tự Tại Vương Như Lai mà phát thệ nguyện rộng lớn rằng:  
  
"Tôi nguyện từ nay nhẫn đến đời vị lai những chúng sanh mắc phải tội khổ, thì tôi lập ra nhiều phương chước làm cho chúng đó được giải thoát."  
  
Đức Phật bảo ngài Văn Thù Sư Lợi rằng: "Quỷ vương Vô Độc trước đó nay chính là ông Tài Thủ Bồ Tát. Còn Thánh nữ Bà La Môn đó nay là Địa Tạng Bồ Tát vậy."  
