# Phân thân tập hội  {#phan-than-tap-hoi}
  
## Hóa thân cùng quyến thuộc  {- #hoa-than-cung-quyen-thuoc}
  
Lúc đó phân thân Địa Tạng Bồ Tát ở các nơi có địa ngục trăm nghìn muôn ức bất khả tư, bất khả nghị, bất khả lượng, bất khả thuyết, vô lượng vô số thế giới đều đến hội họp tại cung trời Đao Lợi.  
  
Do nhờ thần lực của Như Lai, phân thân đó hiệp với những chúng đã được giải thoát ra khỏi chốn nghiệp đạo ở mười phương, cũng đều đông đến số nghìn muôn ức na do tha, đồng cầm hương hoa đến cúng dường Phật.  
  
Những chúng cùng đến với phân thân đó, thảy đều nhờ Địa Tạng Bồ Tát giáo hóa làm cho trụ nơi đạo Vô thượng Chánh đẳng Chánh giác trọn không còn thối chuyển.  
  
Những chúng đó từ kiếp lâu xa cho đến nay trôi lăn trong vòng sanh tử ở trong sáu đường, chịu những điều khổ sở không có lúc nào tạm ngừng dứt, nhờ lòng từ bi lớn và thệ nguyện sâu dày của ngài Địa Tạng Bồ Tát, nên tất cả đều chứng được đạo quả.  
  
Đại chúng đó khi đến cung trời Đao Lợi, lòng họ vui mừng hớn hở, chiêm ngưỡng Đức Như Lai mắt nhìn mãi không rời.  
  
## Đức Như Lai an ủi ủy thác  {- #duc-nhu-lai-an-ui-uy-thac}
  
Bấy giờ, Thế Tôn giơ tay sắc vàng xoa đảnh của hóa thân Địa Tạng đại Bồ Tát trong trăm nghìn muôn ức bất khả tư, bất khả nghị, bất khả lượng, bất khả thuyết, vô lượng vô số thế giới, mà dạy rằng: "Ta ở trong đời ác ngũ trược giáo hóa những chúng sanh cang cường như thế, làm cho lòng chúng nó điều phục bỏ tà về chánh; nhưng trong mười phần vẫn còn một hai phần chúng sanh quen theo tánh ác.  
  
Muốn độ chúng đó, Ta cũng phân nghìn trăm ức thân lập ra nhiều phương chước. Trong chúng sanh đó, hoặc có người căn tánh sáng lẹ nghe pháp của Ta thời liền tín nhận. Hoặc có người phải ân cần khuyên bảo mới thành tựu, được thiện quả. Hoặc có kẻ vì tội nghiệp quá nặng nên chẳng đem lòng kính tin ngưỡng mộ.  
  
Ta phân ra nhiều thân độ thoát những hạng chúng sanh mỗi mỗi sai khác như thế. Hoặc hiện ra thân trai, hoặc hiện ra thân gái, hoặc hiện ra thân Trời, Rồng, hoặc hiện ra thân Quỷ, Thần, hoặc hiện ra rừng, núi, sông, ngòi, ao, rạch, suối, làm lợi ích cho mọi người, để rồi đọ họ được giải thoát.  
  
Hoặc hiện ra thân Thiên Đế, hoặc hiện ra thân trời Phạm Vương, hoặc hiện ra thân vua Chuyển Luân, hoặc hiện ra thân Quốc Vương, hoặc hiện ra thân Cư Sĩ, hoặc hiện ra thân Tể Phụ, hoặc hiện ra thân các hàng quan thuộc, hoặc hiện ra thân Tỳ kheo, Tỳ kheo ni, Ưu bà tắc, Ưu bà di.  
  
Nhẫn đến hiện ra những thân Thanh Văn, La Hán, Bích Chi Phật và Bồ Tát để hóa độ chúng sanh, chớ chẳng phải chỉ có thân Phật hiện ra trước chúng thôi đâu!  
  
Địa Tạng! Ông xem Ta đã trải qua bao số kiếp nhọc nhằn độ thoát những chúng sanh cang cường đầy tội khổ khó khai hóa như thế. Ngoài ra những kẻ chưa điều phục được, thời phải theo nghiệp thọ báo.  
  
Nếu khi chúng nó có bị đọa vào đường dữ chịu nhiều sự thống khổ, thời ông nên nghĩ nhớ Ta ở cung trời Đao Lợi ân cần phó chúc đây mà gắng độ chúng sanh, làm cho chúng sanh trong cõi Ta Bà này đến lúc Phật Di Lặc ra đời, đều đặng giải thoát khỏi hẳn các điều khổ, gặp Phật, được Đức Phật thọ ký."  
  
Bấy giờ, những hóa thân Địa Tạng Bồ Tát ở các thế giới hiệp chung lại một hình, rơi lệ thương cảm mà bạch cùng Đức Phật rằng: "Từ số kiếp lâu xa đến nay, con nhờ Đức Thế Tôn tiếp độ dắt dìu làm cho con được thần lực chẳng thể nghĩ bàn, đầy đủ trí huệ rộng lớn.  
  
Con phân hiện thân hình ra ở cùng khắp trăm nghìn muôn ức hằng hà sa thế giới. Trong mỗi thế giới hóa hiện trăm nghìn muôn ức thân. Mỗi thân đó hóa độ trăm nghìn muôn ức người, làm cho quy kính ngôi Tam Bảo, khỏi hẳn vòng sanh tử hưởng vui Niết Bàn.  
  
Những chúng sanh nào ở nơi Phật pháp chỉ làm việc lành bằng một sợi lông, một giọt nước, một hột cát, một bụi nhỏ, hoặc chỉ bằng chừng mảy lông tóc, con đều độ thoát lần lần, làm cho chúng nó được lợi ích lớn.  
  
Cúi mong Đức Như Lai chớ vì những chúng sanh ác nghiệp trong đời sau mà sanh lòng lo lắng!...  
  
Cúi mong Đức Như Lai chớ vì những chúng sanh ác nghiệp trong đời sau mà sanh lòng lo lắng!..."  
  
Ngài Địa Tạng Bồ Tát bạch cùng Đức Phật ba lần như thế.  
  
Lúc ấy, Đức Phật khen ngài Địa Tạng Bồ Tát rằng: "Hay thay! Hay thay! Ta hộ trợ cho ông được toại nguyện! Từ số kiếp lâu xa đến nay thường phát nguyện rộng lớn, cứu độ tất cả chúng sanh xong rồi, thời ông liền chứng quả Bồ đề."  
