# (PART\*) Quyển Trung {-}

# Danh hiệu của địa ngục { #danh-hieu-cua-dia-nguc}
  
## Phổ Hiền hỏi {- #pho-hien-hoi}
  
Lúc đó, ngài Phổ Hiền Bồ Tát thưa cùng ngài Địa Tạng Bồ Tát rằng: "Thưa Nhơn giả! Xin Ngài vì Trời, Rồng, bát bộ và tất cả chúng sanh ở hiện tại cùng vị lai, mà nói danh hiệu của những địa ngục là chỗ thọ báo của hạng chúng sanh bị tội khổ ở trong cõi Ta Bà cùng Diêm Phù Đề này, và nói những sự về quả báo không lành. Làm cho chúng sanh trong thời Mạt pháp sau này biết rõ những quả báo đó."  
  
Ngài Địa Tạng Bồ Tát đáp rằng: "Thưa Nhơn giả! Nay tôi nương oai thần của Đức Phật cùng oai lực của Ngài mà nói danh hiệu của các địa ngục, cùng những sự về tội báo và ác báo.  
  
## Danh hiệu của địa ngục  {- #danh-hieu-dia-nguc}
  
Thưa Nhơn giả! Phương Đông của Diêm Phù Đề có dãy núi tên là Thiết Vi. Dãy núi đó tối thẳm không có ánh sáng của mặt trời, mặt trăng, trong đó có địa ngục lớn tên là cực Vô Gián.  
  
Lại có địa ngục tên là đại A Tỳ, lại có địa ngục tên là Tứ Giác, lại có địa ngục tên là Phi Đao, lại có địa ngục tên là Hỏa Tiễn, lại có địa ngục tên là Giáp Sơn, lại có địa ngục tên là Thông Thương.  
  
Lại có địa ngục tên là Thiết Xa, lại có địa ngục tên là Thiết Sàng, lại có địa ngục tên là Thiết Ngưu, lại có địa ngục tên là Thiết Y, lại có địa ngục tên là Thiên Nhẫn, lại có địa ngục tên là Thiết Lư.  
  
Lại có địa ngục tên là Dương Đồng, lại có địa ngục tên là Bảo Trụ, lại có địa ngục tên là Lưu Hỏa, lại có địa ngục tên là Canh Thiệt, lại có địa ngục tên là Tỏa Thủ, lại có địa ngục tên là Thiêu Cước.  
  
Lại có địa ngục tên là Đạm Nhãn, lại có địa ngục tên là Thiết Hoàn, lại có địa ngục tên là Tránh Luận, lại có địa ngục tên là Thiết Thù, lại có địa ngục tên là Đa Sân..."  
  
Ngài Địa Tạng Bồ Tát nói rằng: "Thưa Nhơn giả! Trong dãy núi Thiết Vi có những địa ngục như thế số nhiều vô hạn. Lại có địa ngục Kiếu Oán, địa ngục Bạt Thiệt, địa ngục Phẩn Niếu, địa ngục Đồng Tỏa, địa ngục Hỏa Tượng, địa ngục Hỏa Cầu, địa ngục Hỏa Mã, địa ngục Hỏa Ngưu, địa ngục Hỏa Sơn, địa ngục Hỏa Thạch, địa ngục Hỏa Sàng, địa ngục Hỏa Lương, địa ngục Hỏa Ưng, địa ngục Cứ Nha, địa ngục Bác Bì, địa ngục Ẩm Huyết, địa ngục Thiêu Thủ, địa ngục Thiêu Cước, địa ngục Đảo Thích, địa ngục Hỏa Ốc, địa ngục Thiết Ốc, địa ngục Hỏa Lang...  
  
Những địa ngục như thế trong đó mỗi ngục lớn lại có những ngục ngỏ, hoặc một, hoặc hai, hoặc ba, hoặc bốn, nhẫn đến trăm nghìn, trong số đó, danh hiệu đều chẳng đồng nhau."  
  
Ngài Địa Tạng Bồ Tát nói với ngài Phổ Hiền Bồ Tát rằng: "Thưa Nhơn giả! Đó đều là do chúng sanh trong cõi Diêm Phù Đề làm những điều ác mà tùy nghiệp chiêu cảm ra những địa ngục như thế.  
  
Nghiệp lực rất lớn, có thể so sánh với núi Tu Di, có thể sâu dường biển cả, có thể ngăn đạo Thánh.  
  
Vì thế chúng sanh chớ khinh điều quấy nhỏ mà cho là không tội, sau khi chết đều có quả báo, dầu đến mảy mún đều phải chịu lấy.  
  
Chí thân như cha với con, mỗi người cùng theo nghiệp của mình mà đi khác đường, dầu có gặp nhau cũng chẳng bằng lòng chịu khổ thay nhau.  
  
Nay tôi nương oai lực của Đức Phật mà nói sơ lược những sự tội báo nơi địa ngục. Trông mong Nhơn giả tạm nghe lời đó."  
  
Ngài Phổ Hiền Bồ Tát đáp rằng: "Dầu từ lâu tôi đã rõ tội báo nơi ba đường ác đạo rồi, nhưng tôi muốn Nhơn giả nói ra để làm cho tất cả chúng sanh có tâm hạnh ác trong đời Mạt pháp sau này, nghe được lời dạy của Nhơn giả, mà biết quy hướng về giáo pháp của Phật."  
  
## Tội báo trong địa ngục {- #toi-bao-trong-dia-nguc}
  
Ngài Địa Tạng Bồ Tát nói rằng: "Thưa Nhơn giả! Những sự tội báo trong chốn địa ngục như vầy:  
  
Hoặc có địa ngục kéo lưỡi người tội ra mà cho trâu cày trên đó, hoặc có địa ngục moi tim người tội để cho quỷ Dạ Xoa ăn, hoặc có địa ngục vạc dầu sôi sùng sục nấu thân người tội, hoặc có địa ngục đốt cột đồng cháy đỏ rồi bắt người tội ôm lấy.  
  
Hoặc có địa ngục từng bựng lửa lớn bay tấp vào người tội, hoặc có địa ngục toàn cả thuần là băng giá, hoặc có địa ngục đầy vô hạn đồ phẩn tiểu, hoặc có địa ngục lao gai chông sắt, hoặc có địa ngục đâm nhiều giáo lửa.  
  
Hoặc có địa ngục chỉ đập vai lưng, hoặc có địa ngục chỉ đốt chân tay, hoặc có địa ngục cho rắn sắt quấn cắn, hoặc có địa ngục xua đuổi chó sắt, hoặc có địa ngục đóng ách lừa sắt.  
  
Nhơn giả! Những quả báo như thế trong mỗi mỗi ngục có trăm nghìn thứ khí cụ để hành hình, đều bằng đồng, bằng sắt, bằng đá, bằng lửa. Bốn loại khí cụ này là do các hạnh nghiệp quấy ác của chúng sanh mà cảm vời ra.  
  
Nếu tôi thuật rõ cả những sự việc về tội báo ở địa ngục, thời trong mỗi ngục lại còn có trăm nghìn thứ khổ sở, huống chi là nhiều ngục!  
  
Nay tôi nương sức oai thần của Đức Phật và vì Nhơn giả hỏi mà nói sơ lược như thế, Nếu nói rõ cả thời cùng kiếp nói cũng không hết."  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
