# Như Lai tán thán {#nhu-lai-tan-than}
  
## Phật phóng quang dặn bảo {- #phat-phong-quang-dan-bao}
  
Lúc đó, khắp thân của Đức Thế Tôn phóng ra ánh sáng lớn soi khắp đến trăm nghìn muôn ức hằng hà sa cõi nước của chư Phật; trong ánh sáng đó vang ra tiếng lớn bảo khắp các cõi nước của chư Phật rằng:  
  
"Tất cả hàng đại Bồ Tát và Trời, Rồng, Quỷ, Thần v.v... lóng nghe hôm nay Ta khen ngợi rao bày những sự của ngài Địa Tạng Bồ Tát ở trong mười phương thế giới, hiện ra sức từ bi oai thần không thể nghĩ bàn, để cứu giúp tất cả tội khổ chúng sanh.  
  
Sau khi Ta diệt độ, thời hàng Bồ Tát Đại sĩ các ông cùng với Trời, Rồng, Quỷ, Thần v.v... nên dùng nhiều phương chước để giữ gìn Kinh này, làm cho tất cả mọi loài chúng sanh đều khỏi tất cả sự khổ, mà chứng cảnh vui Niết Bàn."  
  
## Phổ Quảng thưa thỉnh {- #pho-quang-thua-thinh}
  
Nói lời ấy xong, trong pháp hội có một vị Bồ Tát tên là Phổ Quảng cung kính chắp tay mà bạch cùng Đức Phật rằng: "Nay con nghe Đức Thế Tôn ngợi khen ngài Địa Tạng Bồ Tát có đức oai thần rộng lớn không thể nghĩ bàn như thế.   
  
Trông mong Đức Như Lai lại vì những chúng sanh trong thời Mạt pháp sau này, mà tuyên nói các sự nhân quả của ngài Địa Tạng Bồ Tát làm lợi ích cho hàng trời, người. Làm cho hàng trời, rồng, bát bộ và chúng sanh trong đời sau kính vâng lời của Đức Phật."  
  
Bấy giờ, Đức Thế Tôn bảo ngài Phổ Quảng Bồ Tát cùng trong tứ chúng rằng: "Lóng nghe! Lóng nghe! Ta sẽ vì các ông nói lược về những sự phước đức của ngài Địa Tạng Bồ Tát làm lợi ích cho người cùng trời."  
  
Ngài Phổ Quảng bạch Phật rằng: "Vâng! Bạch Đức Thế Tôn! Chúng con xin ham muốn nghe."  
  
## Phật dạy sự lợi ích {- #phat-day-su-loi-ich}
  
Đức Phật bảo ngài Phổ Quảng Bồ Tát: "Trong đời sau như có người thiện nam, kẻ thiện nữ nào nghe được danh hiệu của Địa Tạng đại Bồ Tát, hoặc là chắp tay, hoặc là ngợi khen, hoặc là đảnh lễ, hoặc là luyến mộ, người đó sẽ qua khỏi tội khổ trong ba mươi kiếp.  
  
Này Phổ Quảng! Như có kẻ thiện nam hay người thiện nữ nào hoặc là vẽ hình tượng của ngài Địa Tạng Bồ Tát rồi chừng một lần chiêm ngưỡng, một lần đảnh lễ, người đó sẽ được sanh lên cõi trời Đao Lợi một trăm lần, không còn phải bị sa đọa và ác đạo nữa.  
  
Ví dầu ngày kia phước trời đã hết mà sanh xuống nhân gian, cũng vẫn làm vị quốc vương, không hề mất sự lợi lớn.  
  
## Khỏi nữ thân {- #khoi-nu-than}
  
Như có người nữ nào nhàm chán thân gái, hết lòng cúng dường tượng vẽ của Địa Tạng Bồ Tát, và những tượng cất bằng đất đá, keo, sơn, đồng, sắt v.v... Ngày ngày thường đem hoa, hương, đồ ăn, đồ uống, y phục, gấm lụa, tràng phan, tiền bạc, vật báu v.v... cúng dường như thế mãi không thôi.  
  
Người thiện nữ đó sau khi mãn một thân gái hiện tại, thời đến trăm nghìn muôn kiếp còn không sanh vào cõi nước có người nữ, huống nữa là thọ thân gái! Trừ khi vì lòng từ phát nguyện cần phải thọ thân gái để độ chúng sanh. Nương nơi phước cúng dường Địa Tạng Bồ Tát và sức công đức đó, trong trăm nghìn muôn kiếp chẳng còn thọ thân người nữ lại nữa.  
  
## Thân xinh đẹp {- #than-xinh-dep}
  
Lại nữa, này Phổ Quảng Bồ Tát! Nếu có người nữ nào chán thân xấu xí và nhiều bịnh tật, đến nơi trước tượng của ngài Địa Tạng Bồ Tát chí tâm chiêm ngưỡng đảnh lễ chừng trong khoảng một bữa ăn, người nữ đó trong nghìn vạn kiếp thọ sanh được thân hình tướng mạo xinh đẹp không có bịnh tật.  
  
Người nữ xấu xí đó nếu không nhàm thân gái, thời trăm nghìn muôn ức đời thường làm con gái nhà vua cho đến làm vương phi, dòng dõi nhà quan lớn cũng con gái các vị đại Trưởng giả, tướng mạo đoan trang xinh đẹp.  
  
Do vì có lòng chí thành chiêm ngưỡng đảnh lễ hình tượng của ngài Địa Tạng Bồ Tát mà đặng phước như thế.  
  
## Quỷ, thần hộ vệ {- #quy-than-ho-ve}
  
Lại nữa, này Phổ Quảng! Như có người thiện nam, người thiện nữ nào có thể đối trước tượng của Địa Tạng Bồ Tát mà trổi các thứ kỹ nhạc, ngâm ca khen ngợi, dùng hương hoa cúng dường, cho đến khuyến hóa được một người hay nhiều người.  
  
Những hạng người đó ở trong đời hiện tại cùng thời vị lai sau, thường được trăm nghìn vị Quỷ Thần ngày đêm theo hộ vệ, còn không cho những việc hung dữ đến tai người đó, huống là để cho người đó phải chịu các tai vạ bất ngờ!  
  
## Khinh chê mắc tội {- #khinh-che-mac-toi}
  
Lại nữa, này Phổ Quảng Bồ Tát! Trơng đời sau, như các người ác và ác thần, ác quỷ nào thấy kẻ thiện nam, người thiện nữ quy y cung kính, cúng dường ngợi khen chiêm ngưỡng đảnh lễ hình tượng của ngài Địa Tạng Bồ Tát, mà vọng sanh khinh chê là không có công đức cùng không có sự lợi ích hoặc nhăn răng ra cười, hoặc chê sau lưng hay chê trước mặt, hoặc khuyên bảo người khác cùng chê, hoặc khuyên bảo một người cùng chê hay nhiều người cùng chê, cho đến sanh lòng chê bai trong chừng một niệm.  
  
Thời những kẻ như thế đến sau khi một nghìn Đức Phật trong Hiền kiếp nhập diệt cả, bị tội báo khinh chê nên còn ở trong địa ngục A Tỳ chịu tội khổ rất nặng.  
  
Qua khỏi Hiền kiếp này mới được thọ thân ngạ quỷ, rồi mãi đến một nghìn kiếp sau mới thọ thân súc sanh; lại phải trải qua đến một nghìn kiếp nữa mới đặng sanh làm người.  
  
Dầu được làm người nhưng ở vào hạng bần cùng hèn hạ tật nguyền thiếu sứt, hay bị những nghiệp ác ràng buộc vào thân, không bao lâu phải sa đọa vào ác đạo nữa.  
  
Này Phổ Quảng! Khinh chê người khác cúng dường mà còn mắc phải tội báo xấu khổ như thế, huống nữa là tự sanh ác kiến mà khinh chê phá diệt!  
  
## Tiêu tội chướng {- #tieu-toi-chuong}
  
Lại nữa, này Phổ Quảng Bồ Tát! Trong đời sau, như có người nam, người nữ nào đau nằm liệt mãi trên giường gối, cầu sống hay muốn chết cũng đều không được. Hoặc đêm nằm chiêm bao thấy quỷ dữ cho đến kẻ thân thích trong nhà, hoặc thấy đi trên đường nguy hiểm hoặc bị bóng đè, hoặc với quỷ thần cùng đi.  
  
Trải qua nhiều tháng nhiều năm, đến đỗi thành bịnh lao, bịnh dại... Trong giấc ngủ kêu réo thê thảm sầu khổ. Đây đều bị nơi nghiệp đạo luận đối chưa quyết định là khinh hay trọng, nên hoặc là khó chết, hoặc là khó lành.  
  
Mắt phàm tục của kẻ nam, người nữ không thể biện rõ việc đó, chỉ phải nên đối trước tượng của chư Phật Bồ Tát, to tiếng mà đọc Kinh này một biến.  
  
Hoặc lấy những món vật riêng của người bịnh thường ưa tiếc, như y phục, đồ quý báu, nhà cửa, ruộng vườn v.v... đối trước người bịnh cất tiếng lớn mà xướng lên rằng: "Chúng tôi tên đó họ đó, nay vì người bịnh này đối trước Kinh tượng, đem những vật này hoặc cúng dường Kinh tượng, hoặc tạo hình tượng của Phật Bồ Tát, hoặc xây dựng chùa tháp, hoặc sắm đèn dầu thắp cúng, hoặc cúng vào của thường trụ".  
  
Xướng lên như vậy ba lần để cho người bịnh được nghe biết. Giả sử như thần thức của người bịnh đã phân tán đến hơi thở đã dứt, thời hoặc một ngày, hai ngày, ba ngày, bốn ngày cho đến bảy ngày, cứ lớn tiếng xướng bạch như trên và lớn tiếng tụng Kinh này.  
  
Sau khi người bịnh đó mạng chung thời dầu cho từ trước có tội vạ nặng nhẫn đến năm tội Vô Gián, cũng được thoát khỏi hẳn, thọ sanh vào đâu cũng thường nhớ biết việc đời trước.  
  
Huống nữa là người thiện nam, người thiện nữ nào tự mình biên chép Kinh này, hoặc bảo người biên chép, hoặc tự mình đắp vẽ hình tượng của Bồ Tát, người đó khi thọ quả báo chắc đặng nhiều lợi lớn.  
  
Này Phổ Quảng Bồ Tát! Vì thế nên, nếu ông thấy có người nào đọc tụng Kinh này, cho đến chỉ trong một niệm ngợi khen Kinh này, hoặc là có lòng cung kính đối với Kinh, thời ông cần phải dùng trăm nghìn phương chước khuyến hóa người đó, phát lòng siêng năng chớ đừng thối thất, thời có thể được trăm nghìn muôn ức công đức không thể nghĩ bàn ở hiện tại và vị lai.  
  
## Siêu độ vong linh {- #sieu-do-vong-linh}
  
Lại nữa, này Phổ Quảng Bồ Tát! Như những chúng sanh đời sau, hoặc trong giấc ngủ, hoặc trong chiêm bao thấy các hạng quỷ thần nhẫn đến các hình lạ, rồi hoặc buồn bã, hoặc than thở, hoặc hãi hùng, hoặc sợ sệt...  
  
Đó đều là vị hoặc cha mẹ, con em, hoặc chồng vợ, quyến thuộc trong một đời, mười đời hay trăm đời, nghìn đời về thuở quá khứ bị đọa lạc vào ác đạo chưa được ra khỏi, không biết trông mong vào phước lực nơi nào để cứu vớt nỗi khổ não, nên mới về mách bảo với người có tình cốt nhục trong đời trước cầu mong làm phương tiện gì để hầu được thoát khỏi ác đạo.  
  
Này Phổ Quảng! Ông nên dùng sức oai thần, khiến hàng quyến thuộc đó đối trước hình tượng của chư Phật, chư Bồ Tát chí tâm tự đọc Kinh này hoặc thỉnh người khác đọc đủ số ba biến hoặc đến bảy biến.  
  
Như vậy, kẻ quyến thuộc đương mắc trong ác đạo kia, khi tiếng tụng Kinh đủ số mấy biến đó xong sẽ đặng giải thoát, cho đến trong khi mơ ngủ không còn thấy hiện về nữa.  
  
## Khỏi nô lệ {- #khoi-no-le}
  
Lại nữa, này Phổ Quảng! Như đời sau này có những hạng người hà tiện, hoặc tớ trai, hoặc tớ gái, nhẫn đến những kẻ không được quyền tự do, rõ biết là do tội nghiệp đời trước gây ra cần phải sám hối đó, thời nên chí tâm chiêm ngưỡng đảnh lễ hình tượng của ngài Địa Tạng Bồ Tát. Rồi trong bảy ngày niệm danh hiệu của Địa Tạng Bồ Tát đủ một muôn biến.  
  
Những người trên ó sau khi mãn báo thân hạ tiện ở hiện đời, trong nghìn muôn đời về sau thường sanh vào bậc tôn quý, trọn không bao giờ còn phải sao đọa vào ba đường ác khổ nữa.  
  
## Sanh con dễ nuôi {- #sanh-con-de-nuoi}
  
Lại vầy nữa, này Phổ Quảng Bồ Tát! Về trong thuở sau này, nơi cõi Diêm Phù Đề, trong hàng Sát Đế Lợi, Bà La Môn, Trưởng giả, Cư sĩ, tất cả các hạng người và những dân tộc dòng họ khác, như có người nào mới sanh đẻ hoặc con trai hoặc con gái, nội trong bảy ngày, sớm vì đứa trẻ mới sanh ra đó mà tụng Kinh điển không thể nghĩ bàn này, lại vì đứa trẻ mà niệm danh hiệu của ngài Địa Tạng Bồ Tá đủ một muôn biến.  
  
Được vậy thời sanh đứa trẻ hoặc trai hay là gái mới sanh ra đó, nếu đời trước nó có gây lấy tội vạ chi cũng đặng thoát khỏi cả, nó sẽ an ổn vui vẻ dễ nuôi, lại thêm được sống lâu.  
  
Còn như nó là đứa nương nơi phước lực mà thọ sanh, thời đời nó càng được an vui hơn cùng sống lâu hơn.  
  
## Ngày thập trai tụng kinh được phước {- #ngay-thap-trai-tung-kinh-duoc-phuoc}
  
Lại vầy nữa, này Phổ Quảng! Trong mỗi tháng những ngày: mùng một, mùng tám, mười bốn, rằm, mười tám, hăm ba, hăm bốn, hăm tám, hăm chín và ba mươi, mười ngày trên đây là ngày mà các nghiệp tội kết nhóm lại để định là nặng hay nhẹ.  
  
Tất cả những cử chỉ động niệm của chúng sanh trong cõi Nam Diêm Phù Đề không có điều gì chẳng phải là tội lỗi, huống nữa là những kẻ buông lung giết hại, trộm cắp, tà dâm, vọng ngữ trăm điều tội lỗi.  
  
Về đời sau, nếu có chúng sanh nào trong mười ngày trai kể trên đây, mà có thể đối trước hình tượng của chư Phật, Bồ Tát, Hiền, Thánh để đọc tụng Kinh này một biến, thời chung quanh chỗ người đó ở bốn hướng Đông, Tây, Nam, Bắc trong khoảng một trăm do tuần không có xảy ra những việc tai nạn.  
  
Còn chính nhà của người đó ở, tất cả mọi người hoặc già, hoặc trẻ về hiện tại và vị lai đến trăm nghìn năm xa khỏi hẳn các ác đạo.  
  
Trong mười ngày trai trên đây nếu có thể mỗi ngày tụng một biến Kinh này, thời trong đời hiện tại hay làm cho người trong nhà không mắc phải bịnh tật bất ngờ, đồ ăn mặc dư dật.  
  
Này Phổ Quảng! Vì thế nên biết rằng ngài Địa Tạng Bồ Tát có bất khả thuyết trăm nghìn muôn ức những sự oai thần lực lớn, nhiều lợi ích cho chúng sanh như thế.  
  
Chúng sanh trong cõi Diêm Phù Đề này có nhơn duyên lớn với ngài Địa Tạng Đại sĩ. Những chúng sanh đó hoặc được nghe danh hiệu của Địa Tạng Bồ Tát, hoặc được thấy hình tượng của Địa Tạng Bồ Tát, cho đến nghe chừng ba chữ hay năm chữ trong Kinh này, hoặc một bài kệ hay một câu, thời những người đó hưởng sự an vui lạ thường trong đời hiện tại, trăm nghìn muôn đời về vị lai thường được thác sanh vào nhà tôn quý, thân hình xinh đẹp."  
  
## Danh hiệu của Kinh {- #danh-hieu-cua-kinh}
  
Khi nghe Đức Phật Như Lai tuyên bày ngợi khen ngài Địa Tạng Đại sĩ xong, ngài Phổ Quảng Bồ Tát liền quỳ xuống chắp tay mà bạch cùng Đức Phật rằng: "Bạch Thế Tôn! Từ lâu con đã rõ biết vị Đại sĩ này có thần lực cùng đại nguyện lực không thể nghĩ bàn như thế rồi, song nay vì muốn những chúng sanh trong đời sau này rõ biết các sự lợi ích đó, nên con mới bạch hỏi cùng Đức Như Lai.  
  
Vâng! Con xin cung kính tin nhận lời Phật dạy.  
  
Bạch Đức Thế Tôn! Kinh này đặt tên là gì và định cho con lưu bố thế nào?"  
  
Đức Phật bảo ngài Phổ Quảng: "Kinh này có ba danh hiệu: một là "Địa Tạng Bổn Nguyện Kinh", cũng gọi là "Địa Tạng Bổn Hạnh Kinh" đây là tên thứ hai, cũng gọi là "Địa Tạng Bổn Thệ Lực Kinh" đây là tên thứ ba.  
  
Do vì ngài Địa Tạng Bồ Tát từ thuở kiếp lâu xa đến nay phát nguyện rộng lớn làm lợi ích cho chúng sanh, cho nên các ông phải đúng theo tâm nguyện mà lưu hành truyền bá Kinh này."  
  
Nghe Đức Phật dạy xong, ngài Phổ Quảng Bồ Tát tin chịu, chắp tay cung kính lễ Phật mà lui ra.  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
