# (PART\*) Quyển Hạ {-}

# So sánh nhơn duyên công đức của sự bố thí {#so-sanh-nhon-duyen-cong-duc-cua-su-bo-thi}
  
Lúc đó, ngài Địa Tạng Bồ Tát Ma ha tát nương oai thần của Đức Phật, từ chỗ ngồi đứng dậy, quỳ gối chắp tay bạch cùng Đức Phật rằng:  
  
"Bạch Đức Thế Tôn! Con xem xét chúng sanh trong nghiệp đạo so sánh về sự bố thí có nhẹ có nặng. Có người hưởng phước trong một đời, có người hưởng phước trong mười đời, hoặc đến hưởng phước lợi lớn trong trăm đời, nghìn đời.  
  
Những sự ấy tại làm sao thế? Cúi xin Đức Thế Tôn dạy cho."  
  
Bấy giờ, Đức Phất bảo ngài Địa Tạng Bồ Tát rằng: "Nay Ta ở trong toàn thể chúng hội nơi cung trời Đao Lợi này giảng về sự so sánh công đức khinh trọng của việc bố thí ở Diêm Phù Đề. Ông phải lóng nghe, Ta sẽ vì ông mà nói!"  
  
Ngài Địa Tạng Bồ Tát bạch cùng Đức Phật rằng: "Chính con nghi ngờ việc ấy. Con xin ưa muốn nghe."  
  
Đức Phật bảo ngài Địa Tạng Bồ Tát rằng: "Trong cõi Nam Diêm Phù Đề có các vị Quốc vương, hàng Tể phụ quan chức lớn, hàng đại Trưởng giả, hàng đại Sát Đế Lợi, hàng đại Bà La Môn v.v...  
  
Nếu gặp kẻ hết sức nghèo túng, nhẫn đến kẻ tật nguyền câm ngọng, kẻ điếc ngây mù quáng, gặp những hạng người thân thể không được vẹn toàn như thế.  
  
Lúc các vị Quốc vương đó v.v... muốn bố thí, nếu có thể đủ tâm từ bi lớn, lại có lòng vui vẻ tự hạ mình, tự tay mình đem của ra bố thí cho tất cả những kẻ đó, hoặc bảo người khác đem cho, lại dùng lời ôn hòa dịu dàng an ủi.  
  
Các vị Quốc vương, Đại thần đó v.v... đặng phước lợi bằng phước lợi công đức cúng dường cho một trăm hàng hà sa chư Phật vậy.  
  
Tại làm sao? Chính bởi vị Quốc vương đó v.v... phát tâm đại từ bi đối với kẻ rất mực nghèo cùng và với những người tàn tật kia, cho nên phước lành được hưởng quả báo như thế này, trong trăm nghìn đời thường được đầy đủ những đồ thất bảo, huống là những thứ để thọ dùng như y phục đồ uống ăn v.v...  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có vị Quốc vương cho đến hàng Bà La Môn v.v... gặp chùa tháp thờ Phật, hoặc hình tượng Phật, cho đến hình tượng Bồ Tát, Thanh Văn hay Bích Chi Phật, đích thân tự sửa sang, cúng dường bố thí.  
  
Vị Quốc vương đó, sẽ đặng trong ba kiếp làm vị trời Đế Thích hưởng sự vui sướng tốt lạ.  
  
Nếu có thể đem phước lành bố thí đó mà hồi hướng cho tất cả chúng sanh trong pháp giới, thời vị Quốc vương đó, trong mười kiếp thường được làm vị trời Đại Phạm Thiên vương.  
  
Lại thế này nữa, này Địa Tạng Bồ Tát! Trong đời sau, nếu có vị Quốc Vương cho đến hàng Bà La Môn v.v... Gặp chùa tháp của Đức Phật thưở trước, hoặc là Kinh điển hay hình tượng bị hư sụp rách rã, liền có thể phát tâm tu bổ lại.  
  
Vị Quốc vương đó, hoặc tự mình đích thân lo sửa sang, hoặc khuyến hóa người khác cho đến khuyến hóa trăm nghìn người khác cùng chung bố thí cúng dường để kết duyên lành.  
  
Vị Quốc vương đó, trong trăm nghìn đời thường làm vua Chuyển Luân, còn những người khác chung cùng làm việc bố thí đó, trong trăm nghìn đời thường làm vua nước nhỏ.  
  
Nếu lại ở trước chùa tháp có thể phát tâm đem công đức cúng dường bố thí đó mà hồi hướng về đạo Vô thượng Chánh giác, được như vậy thời vị Quốc vương đó cho đến tất cả mọi người đều sẽ thành Phật cả, bởi quả báo ấy rộng lớn vô lượng vô biên.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có vị Quốc vương hay hàng Bà La Môn, gặp những người già yếu tật bịnh và kẻ phụ nữ sanh đẻ, nếu trong khoảng chừng một niệm sanh lòng từ lớn đem thuốc men, cơm nước, giường chiếu bố thí, làm cho những kẻ ấy được an vui.  
  
Phước đức đó rất không thể nghĩ bàn đến được, trong một trăm kiếp thường làm vua trời Tịnh Cư, trong hai trăm kiếp thường làm vua sáu từng trời cõi Dục, không bao giờ còn đọa vào ác đạo, cho đến trong trăm nghìn đời, lỗ tai không hề nghe đến tiếng khổ, rốt ráo sẽ thành Phật đạo.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau như có vị Quốc vương và Bà La Môn, có thể làm những việc bố thí như thế sẽ đặng vô lượng phước lành.  
  
Nếu lại có thể đem phước đức đó hồi hướng đạo Bồ đề, thời không luận là nhiều hay ít, rốt ráo sẽ thành Phật cả, huống gì là những quả trời Phạm Vương, trời Đế Thích, vua Chuyển Luân.  
  
Này Địa Tạng Bồ Tát! Vì thế nên khuyến hóa tất cả chúng sanh đều phải học theo như thế.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có thiện nam kẻ thiện nữ nào ở trong Phật pháp mà gieo trồng chút ít cội phước lành chừng bằng cái lông, sợi tóc, hột cát, mảy bụi, phước lợi của những người đó sẽ hưởng thọ không thể ví dụ thế nào cho được.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có kẻ thiện nam cùng người thiện nữ nào gặp hình tượng Phật, hình tượng Bồ Tát, hình tượng Bích Chi Phật, hình tượng vua Chuyển Luân mà bố thí cúng dường, thời đặng vô lượng phước lành, thường sanh ở cõi người, cõi trời hưởng sự vui thù thắng vi diệu.  
  
Như có thể đem công đức hồi hướng cho cả pháp giới chúng sanh, thời phước lợi của người ấy không thể ví dụ thế nào cho được.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có kẻ thiện nam người thiện nữ nào gặp Kinh điển Đại thừa hoặc nghe thấy một bài kệ, một câu Kinh, rồi phát tâm ân cần trân trọng cung kính ngợi khen, bố thí cúng dường, người ấy được quả báo vô lượng vô biên.  
  
Nếu có thể đem phước đức hồi hướng cho khắp pháp giới chúng sanh thời phước lợi này không thể ví dụ thế nào cho được.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có kẻ thiện nam người thiện nữ nào, gặp chùa tháp và Kinh điển Đại thừa, nếu là Kinh tháp mới thời bố thí cúng dường, chiêm ngưỡng lễ lạy ngợi khen chắp tay cung kính.  
  
Nếu gặp Kinh tháp cũ, hoặc hư rách thời sửa sang tu bổ, hoặc riêng mình phát tâm làm, hoặc khuyến người khác cùng đồng phát tâm.  
  
Những người đồng phát tâm đây, trong ba mươi đời thường làm vua các nước nhỏ. Còn vị Đàn việt chính đó thường làm vua Chuyển Luân, lại dùng pháp lành mà giáo hóa vua các nước nhỏ.  
  
Lại vầy nữa, này Địa Tạng Bồ Tát! Trong đời sau, như có người thiện nam kẻ thiện nữ nào, ở nơi cội phước lành đã gieo trồng trong Phật pháp, hoặc là bố thí cúng dường, hoặc là tu bổ chùa tháp, hoặc sửa sang Kinh điển, cho đến chừng bằng một sợi lông, một mảy bụi, một hột cát, một giọt nước.  
  
Những sự lành như thế không luận nhiều ít, chỉ có thể đem hồi hướng cho khắc pháp giới chúng sanh, thời công đức của người đó trong trăm nghìn đời thường hưởng thọ sự vui thượng diệu.  
  
Còn như chỉ hồi hướng cho thân quyến trong nhà hoặc tự mình được lợi ích thôi, như thế thời sẽ hưởng quả vui trong ba đời, cứ làm một phần sự lành, thời được hưởng báo tốt một muôn lần trội hơn.  
  
Này Địa Tạng Bồ Tát! Những nhơn duyên công đức về sự bố thí như thế đó."  
