# Địa thần hộ pháp {#dia-than-ho-phap}
  
Lúc đó, vị Kiên Lao Địa Thần bạch cùng Đức Phật rằng: "Bạch Đức Thế Tôn! Từ trước đến nay, con từng chiêm ngưỡng đảnh lễ vô lượng vị đại Bồ Tát, đều là những bậc trí huệ thần thông lớn không thể nghĩ bàn độ khắp mọi loài chúng sanh.  
  
Ngài Địa Tạng Bồ Tát đây so với các vị Bồ Tát chỗ thệ nguyện rất là sâu rộng.  
  
Bạch Đức Thế Tôn! Ngài Địa Tạng Bồ Tát đây có nhơn duyên lớn với chúng sanh trong cõi Diêm Phù Đề.  
  
Như ngài Văn Thù, ngài Phổ Hiền, ngài Quan Âm, ngài Di Lặc cũng hóa hiện trăm nghìn thân hình để độ chúng sanh trong sáu đường, nhưng chỗ phát nguyện của các Ngài còn có lúc hoàn mãn.  
  
Ngài Địa Tạng Bồ Tát đây phát thệ nguyện giáo hóa tất cả chúng sanh trong sáu đường trải đến kiếp số như số cát trong trăm nghìn ức sông Hằng.  
  
Bạch Đức Thế Tôn! Con xem xét chúng sanh ở hiện tại nay và về vị lai sau, nơi chỗ sạch sẽ ở phương Nam trong cuộc đất của mình ở, dùng đất đá, tre gỗ mà dựng cất cái khám cái thất.  
  
Trong đó có thể họa vẽ, cho đến dùng vàng, bạc, đồng, sắt đúng nắn hình tượng Địa Tạng Bồ Tát, đốt hương cúng dường, chiêm lễ ngợi khen, thời chỗ người đó ở được mười điều lợi ích.  
  
Những gì là mười điều?  
Một là đất cát tốt mầu,  
Hai là nhà cửa an ổn mãi mãi,  
Ba là người đã chết được sanh lên cõi Trời,  
Bốn là những người hiện còn hưởng sự lợi ích,  
Năm là cầu chi cũng toại ý cả,  
Sáu là không có tai hoạ về nước và lửa,  
Bảy là trừ sạch việc hư hao,  
Tám là dứt hẳn ác mộng,  
Chín là khi ra lúc vào có thần theo hộ vệ,  
Mười là thường gặp bậc Thánh nhơn.  
  
Bạch Đức Thế Tôn! Chúng sanh trong đời sau cùng hiện tại nay, nếu ở nơi phần đất của mình cư trụ mà có thể làm ra sự cúng dường ngài Địa Tạng như thế, thời được sự lợi ích như vậy."  
  
Vị Kiên Lao Địa Thần lại bạch với Đức Phật rằng:  
  
"Bạch Đức Thế Tôn! Trong đời sau này, như có người thiện nam kẻ thiện nữ nào, ở trong chỗ của mình cư trụ mà có Kinh điển này cùng hình tượng của ngài Địa Tạng Bồ Tát, người đó lại có thể đọc tụng Kinh điển này và cúng dường hình tượng của Bồ Tát.  
  
Thời con dùng thần lực của con thường hộ vệ người đó, cho đến tất cả sự tai họa như nước, lửa, trộm cướp, nạn lớn, nạn nhỏ v.v... thảy đều tiêu sạch."  
  
Đức Phật bảo Kiên Lao Địa Thần rằng: "Thần lực rộng lớn của ông, các thần khác ít ai bằng.  
  
Vì cớ sao? Vì đất đai trong cõi Diêm Phù Đề đều nhờ ông hộ trợ, cho đến cây cỏ, cát đá, lúa mè, tre lau, gạo thóc, của báu, tất cả những thứ từ đất mà có ra đều nhờ nơi sức thần của ông cả.  
  
Nay ông lại tuyên bày những sự lợi ích của ngài Địa Tạng Bồ Tát, thời công đức và thần thông của ông lại càng thêm trăm nghìn lần trội hơn lúc thường.  
  
Này Địa Thần! Trong đời sau, như có kẻ thiện nam người thiện nữ nào cúng dường Địa Tạng Bồ Tát cùng đọc tụng Kinh điển này, chỉ có thể tu hành theo một việc mà trong Kinh "Địa Tạng Bồ Tát Bổn Nguyện" đã dạy.  
  
Thời ông nên dùng thần lực của ông mà ủng hộ người đó, chớ để tất cả sự tai hại cùng sự không vừa ý đến nghe nơi tai, huống nữa là để cho phải chịu.  
  
Chẳng phải chỉ riêng mình ông hộ trì người đó, cũng có hàng quyến thuộc của Phạm Vương, Đế Thích, quyến thuộc của chư Thiên ủng hộ người đó.  
  
Tại sao lại đặng các vị Hiền Thánh ủng hộ như thế?  
  
Đều do vì những người ấy chiêm lễ hình tượng Địa Tạng Bồ Tát và đọc tụng Kinh "Bổn Nguyện" này, tự nhiên được rốt ráo xa lìa biển khổ chứng đạo Niết Bàn an vui, vì thế nên đặng ủng hộ một cách lớn lao như thế."  
  
