# Thấy nghe được lợi ích {#thay-nghe-duoc-loi-ich}
  
## Đức Phật phóng quang tuyên cáo {- #duc-phat-phong-quang-tuyen-cao}
  
Lúc đó, từ trên đảnh môn, Đức Thế Tôn phóng ra cả trăm nghìn muôn ức tia sáng lớn.  
  
Như là: Tia sáng sắc trắng, tia sáng sắc trắng lớn, tia sáng lành tốt, tia sáng lành tốt lớn, tia sáng ngọc, tia sáng ngọc lớn, tia sáng sắc tía, tia sáng sắc tía lớn, tia sáng sắc xanh, tia sáng sắc xanh lớn, tia sáng sắc biếc, tia sáng sắc biếc lớn, tia sáng sắc hồng, tia sáng sắc hồng lớn, tia sáng màu lục, tia sáng màu lục lớn, tia sáng màu vàng y, tia sáng màu vàng y lớn, tia sáng tướng mây lành, tia sáng tướng mây lành lớn, tia sáng tướng nghìn vòng tròn, tia sáng tướng nghìn vòng tròn lớn, tia sáng vòng tròn báu, tia sáng vòng tròn báu lớn, tia sáng vừng mặt trời, tia sáng vừng mặt trời lớn, tia sáng vừng mặt trăng, tia sáng vừng mặt trăng lớn, tia sáng tướng cung điện, tia sáng tướng cung điện lớn, tia sáng tướng mây biển, tia sáng tướng mây biển lớn.  
  
Từ trên đảnh môn phóng ra những luồng tia sáng như thế xong, lại nói ra những tiếng vi diệu mà bảo đại chúng rằng:  
  
"Này tám bộ chúng Trời, Rồng, người cùng phi nhơn v.v...! Lóng nghe hôm nay Ta ở tại cung trời Đao Lợi tuyên bày ngợi khen những sự lợi ích trong hàng trời người, những sự không thể nghĩ bàn, những sự về nhơn hạnh lên bậc Thánh, những sự chứng quả Thập địa, những sự rốt ráo không lui sụt nơi đạo Vô thượng Chánh đẳng Chánh giác... của ngài Địa Tạng Bồ Tát."  
  
## Quán Thế Âm cầu thỉnh {- #quan-the-am-cau-thinh}
  
Lúc Đức Phật nói lời trên đó vừa dứt tiếng, trong pháp hội có một vị đại Bồ Tát hiệu là Quán Thế Âm, từ chỗ ngồi đứng dậy, quỳ gối chắp tay mà bạch cùng Đức Phật rằng:  
  
"Bạch Đức Thế Tôn! Ngài Địa Tạng đại Bồ Tát đầy đủ đức từ bi lớn, Ngài thương xót chúng sanh mắc tội khổ ở trong muôn nghìn ức thế giới, Ngài hóa hiện ra nghìn muôn ức thân, bao nhiêu công đức và sức oai thần chẳng thể nghĩ bàn của Ngài, con đã từng nghe Đức Thế Tôn cùng vô lượng chư Phật trong mười phương, khác miệng đồng lời ngợi khen ngài Địa Tạng Bồ Tát.  
  
Dầu cho các Đức Phật trong thuở quá khứ, thuở hiện tại và thuở vị lai nói công đức của ngài Địa Tạng Bồ Tát vẫn chẳng thể nói hết.  
  
Vừa rồi lại được Đức Thế Tôn bảo khắp trong đại chúng rằng Đức Phật muốn tuyên nói các sự lợi ích của ngài Địa Tạng Bồ Tát.  
  
Cúi mong Đức Thế Tôn vì tất cả chúng sanh ở hiện tại và vị lai mà tuyên nói những sự chẳng thể nghĩ bàn của ngài Địa Tạng Bồ Tát, làm cho tám bộ chúng Trời, Rồng, v.v... chiêm ngưỡng lễ lạy ngài Địa Tạng Bồ Tát để đặng phước lành."  
  
## Đức Phật tán thán và hứa khả {- #duc-phat-tan-than-va-hua-kha}
  
Đức Phật bảo ngài Quán Thế Âm Bồ Tát: "Ông có nhơn duyên rất lớn với chúng sanh trong cõi Ta Bà. Những hàng Trời, Rồng, hoặc nam tử nữ nhơn, hoặc Thần, hoặc Quỷ, cho đến chúng sanh mắc phải tội khổ trong sáu đường nếu kẻ nào nghe danh hiệu của ông, thấy hình tượng của ông, hay mến tưởng đến ông cùng khen ngợi ông.  
  
Thời chúng sanh ấy đều ở nơi đạo Vô thượng Chánh giác quyết chẳng còn thối chuyển, thường được sanh vào cõi người, cõi trời hưởng đủ sự vui vi diệu, khi nhân quả sắt thành thục liền được Phật thọ ký cho.  
  
Nay ông sẵn lòng từ bi lớn thương xót các loài chúng sanh và tám bộ chúng Trời, Rồng v.v... mà muốn nghe Ta nói những sự lợi ích chẳng thể nghĩ bàn của ngài Địa Tạng Bồ Tát.  
  
Ông nên lóng nghe cho kỹ, nay Ta sẽ nói đó!"  
  
Ngài Quán Thế Âm Bồ Tát bạch rằng: "Vâng! Bạch Đức Thế Tôn! Con xin ưa muốn nghe."  
  
## Thấy nghe thêm phước trời {- #thay-nghe-them-phuoc-troi}
  
Đức Phật bảo ngài Quán Thế Âm Bồ Tát: "Trong các thế giới về thuở hiện tại nay và vị lai sau, có vị trời nào, hưởng phước trời đã mãn, năm tướng suy hao hiện ra nơi thân, hoặc có kẻ phải đọa lạc nơi chốn ác đạo.  
  
Các vị trời đó, hoặc nam hoặc nữ đương lúc tướng suy hao hiện, hoặc thấy hình tượng của ngài Địa Tạng Bồ Tát, rồi một lần chiêm ngưỡng một lần đảnh lễ.  
  
Thời các vị trời đó càng thêm lớn phước trời, hưởng sự vui sướng rất nhiều không bao giờ còn phải bị đọa lạc vào ba ác đạo nữa.  
  
Huống chi là những người thấy hình tượng Bồ Tát, nghe danh hiệu Bồ Tát, rồi đem các thứ hương hoa, đồ y phục, đồ uống ăn, vật báu, chuỗi ngọc... mà bố thí cúng dường, thời người này đặng vô lượng vô biên công đức phước lợi.  
  
## Người bịnh được lợi {- #nguoi-binh-duoc-loi}
  
Lại vầy nữa, này Quán Thế Âm! Trong các thế giới về thuở hiện tại nay và vị lai sau, những hàng chúng sanh trong sáu đường, như có kẻ sắp mạng chung mà đặng nghe một tiếng danh hiệu của ngài Địa Tạng Bồ Tát thoáng qua lỗ tai, thì kẻ mạng chúng đó không còn bị đọa vào chốn khổ ba ác đạo.  
  
Huống chi là lúc sắp mạng chung, cha mẹ cùng hàng thân quyến đem của cải nhà cửa, vật báu, y phục v.v... của người sắp mạng chung đó mà làm chi phí để tô đắp hay hoạ vẽ hình tượng của ngài Địa Tạng Bồ Tát.  
  
Rồi làm cho người bịnh lúc chưa chết, hoặc mắt thấy tai nghe biết rằng hàng thân quyến đem nhà cửa, vật báu v.v... vì mình mà tô vẽ hình tượng của ngài Địa Tạng Bồ Tát.  
  
Người bịnh đó nếu có nghiệp báo phải mang lấy bịnh nặng, thời nhờ công đức này liền được lành mạnh, tuổi thọ thêm lâu.  
  
Còn nếu người bịnh đó có nghiệp báo số mạng đã hết, lại có đủ tất cả tội chướng, nghiệp chướng đáng lẽ phải đọa vào chốn ác đạo, song vì nhờ công đức này nên sau khi mạng chung, liền được sanh vào cõi trời, cõi người hưởng quả vui thù thắng vi diệu, tất cả tội chướng thảy đều tiêu sạch.  
  
## Tiên vong được phước {- #tien-vong-duoc-phuoc}
  
Lại vầy nữa, này Quán Thế Âm Bồ Tát! Về đời sau, nếu có kẻ nam tử, người nữ nhơn nào, hoặc lúc còn bú mớm, hoặc lúc lên ba tuổi, hoặc lúc lên năm tuổi, mười tuổi trở xuống mà chết mất cha mẹ cho đến chết mất anh em chị em.  
  
Đến khi người đó khôn lớn nhớ tưởng đến cha mẹ cùng hàng thân quyến không rõ đọa lạc vào chốn nào, hay sanh về thế giới nào, hoặc sanh lên cõi trời nào?  
  
Người đó như có thể tô vẽ hình tượng của ngài Địa Tạng Bồ Tát, nhẫn đến nghe danh hiệu của Ngài rồi một lần chiêm ngưỡng một lần đảnh lễ, từ một ngày cho đến bảy ngày đừng thối thất tâm ban đầu, nghe danh hiệu thấy hình tượng chiêm lễ cúng dường.  
  
Thời quyến thuộc đã sớm khuất của người đó nếu do ác nghiệp mà bị đọa vào ác đạo, tính ra phải chịu đến số kiếp, nay nhờ công đức tô vẽ hình tượng của ngài Địa Tạng Bồ Tát và chiêm lễ cúng dường của con cái, hay của anh em chị em, nên liền đặng giải thoát, được sanh lên cõi trời cõi người hưởng quả vui thù thắng vi diệu.  
  
Còn như quyến thuộc đã sớm khuất của người đó có phước lành, đã được sanh lên cõi trời cõi người hưởng thọ quả vui thù thắng vi diệu rồi, thời nhờ công đức này càng thêm lớn nghiệp nhân về bậc Thánh, hưởng vô lượng quả vui.  
  
Như người đó lại có thể trong hai mươi mốt ngày, chuyên lòng chiêm lễ hình tượng của ngài Địa Tạng Bồ Tát và niệm lấy danh hiệu của Ngài đủ số một muôn biến, sẽ đặng Địa Tạng Bồ Tát hiện vô biên thân, mách cho người đó rõ nơi cõi của hàng thân quyến sớm khuất kia đã sanh về.  
  
Hoặc trong giấc mộng, Địa Tạng Bồ Tát hiện sức thần thông lớn, tự dắt người đó đến các thế giới thấy hàng quyến thuộc.  
  
Nếu người đó lại có thể trong mỗi ngày niệm danh hiệu của Bồ Tát một nghìn biến luôn đến một nghìn ngày.  
  
Thời người đó sẽ được Bồ Tát sai các vị Quỷ Thần ở tại chỗ đó hộ vệ trọn đời, hiện đời món ăn đồ mặc dư dật, không có các thứ bịnh khổ, cho đến các sự tai vạ còn không hề vào đến cửa, huống nữa là đến nơi thân.  
  
Rốt ráo rồi người đó được ngài Địa Tạng Bồ Tát xoa đảnh thọ ký cho.  
  
## Nguyện lớn sớm thành {- #nguyen-lon-som-thanh}
  
Lại vầy nữa, này Quán Thế Âm Bồ Tát! Về đời sau, như có kẻ thiện nam người thiện nữ nào muốn phát lòng từ rộng lớn để cứu độ tất cả chúng sanh, muốn tu đạo Vô thượng Chánh giác, muốn thoát khỏi Tam giới.  
  
Những người đó thấy hình tượng và nghe danh hiệu của ngài Địa Tạng Bồ Tát, rồi chí tâm quy y hoặc đem hương hoa, y phục, vật báo, đồ ăn uống v.v... để cúng dường chiêm ngưỡng đảnh lễ, thời chỗ nguyện cầu của kẻ thiện nam cùng thiện nữ đó mau được thành tựu không bao giờ bị chướng ngại.  
  
Lại vầy nữa, này Quán Thế Âm Bồ Tát! Trong đời sau, như có kẻ thiện nam, người thiện nữ nào, muốn cầu trăm nghìn muôn ức điều nguyện, trăm nghìn muôn ức sự về hiện tại cùng vị lai, thời chỉ nên quy y chiêm ngưỡng đảnh lễ, cũng dường, ngợi khen hình tượng của ngài Địa Tạng Bồ Tát.  
  
Được như thế thời nguyện những chi và cầu những chi thảy đều thành tựu cả.  
  
Lại cầu mong Địa Tạng Bồ Tát, vận đức từ bị rộng lớn ủng hộ mãi cho, người đó trong giấc chiêm bao liền đặng ngài Địa Tạng Bồ Tát xoa đảnh thọ ký.  
  
## Được trí huệ {- #duoc-tri-hue}
  
Lại vầy nữa, này Quán Thế Âm Bồ Tát! Trong đời sau, như có người thiện nam, kẻ thiện nữ nào sanh lòng rất trân trọng đối với Kinh điển Đại thừa, phát tâm bất tư nghị muốn đọc muốn tụng Kinh điển ấy.  
  
Dầu gặp đặng bậc Minh sư truyền dạy cho những người đó học tập, nhưng đọc rồi quên rồi, trải đến cả tháng cả năm vẫn không đọc tụng được.  
  
Những kẻ thiện nam đó vì có nghiệp chướng đời trước chưa trừ sạch, cho nên ở nơi Kinh điển Đại thừa không có công năng đọc tụng.  
  
Những hạng người này khi nghe danh hiệu của ngài Địa Tạng Bồ Tát cùng thấy hình tượng của ngài Địa Tạng Bồ Tát, đem hết bổn tâm cung kính bày tỏ với Bồ Tát, rồi dùng hương hoa, y phục, đồ ăn, tất cả đồ ngọa cụ, v.v... cúng dường hình tượng Bồ Tát.  
  
Dùng một chén nước trong để trước tượng Bồ Tát một ngày một đêm, sau đó cung kính chắp tay thỉnh để uống, xây mặt về hướng Nam.  
  
Khi nước vào miệng phải chí tâm trịnh trọng, uống nước xong, phải cữ ngũ tân, rượu, thịt, tà dâm, vọng ngữ và việc giết hại trong bảy ngày hoặc hai mươi mốt ngày.  
  
Người thiện nam cùng thiện nữ đó trong giấc chiêm bao thấy Địa Tạng Bồ Tát hiện thân vô biên rưới nước trên đảnh của người đó.  
  
Sau khi thức dậy, người đó liền đặng thông minh, một phen nghe đến những Kinh điển Đại thừa ấy liền sẽ nhớ mãi, không bao giờ còn quên một câu kệ nữa.  
  
## Tai nạn tiêu trừ {- #tai-nan-tieu-tru}
  
Lại vầy nữa, này Quán Thế Âm Bồ Tát! Về trong đời sau, như có người nào ăn mặc không đủ, cầu chi cũng không toại nguyện, hoặc thân nhiều tật bịnh, hoặc nhiều sự hung suy, nhà cửa không yên ổn, quyến thuộc chia lìa, hoặc các sự tai vạ cứ đến khuấy nhiễu nơi thân luôn, trong giấc mộng thường phải kinh sợ.  
  
Những người như thế đó, khi nghe danh hiệu của ngài Địa Tạng Bồ Tát, thấy hình tượng của ngài Địa Tạng Bồ Tát nên chí tâm cung kính niệm đủ một muôn biến, thời những sự không toại ý trên đó sẽ tiêu sạch lần lần, liền đặng an vui, đồ ăn mặc dư dật, cho đến trong giấc mộng thảy đều an ổn vui vẻ.  
  
## Khỏi hiểm nguy {- #khoi-hiem-nguy}
  
Lại vầy nữa, này Quán Thế Âm Bồ Tát! Về đời sau, nếu có người thiện nam thiện nữ nào, hoặc nhơn sự làm ăn, hoặc nhơn sự công chuyện tư, hoặc nhơn sự sanh cùng tử, hoặc nhơn việc gấp mà phải vào trong rừng núi, hay là qua sông vượt biển hoặc gặp nước lụt lớn, hoặc đi ngang đường hiểm trở.  
  
Người ấy trước khi đi nên niệm danh hiệu của ngài Địa Tạng Bồ Tát một muôn biến, được thế thời đi qua nơi nào chốn nào cũng có các vị Quỷ Thần hộ vệ, lúc đi đứng, khi nằm ngồi, đều được an ổn vui vẻ luôn, cho đến dầu gặp loài hùm sói sư tử... nhưng tất cả thứ độc hại đều không thể phạm đến người đó được."  
  
Đức Phật bảo ngài Quán Thế Âm Bồ Tát: "Ngài Địa Tạng Bồ Tát có nhơn duyên rất lớn với cõi Diêm Phù Đề. Nếu nói về những sự mà các hàng chúng sanh thấy hình nghe tên của ngài Địa Tạng Bồ Tát được lợi ích, thời dầu nói đến trong trăm nghìn kiếp cũng không hết được.  
  
Này Quán Thế Âm Bồ Tát! Vì thế ông nên dùng thần lực mà lưu truyền Kinh này làm cho chúng sanh trong cõi Ta Bà đây mãi đến trăm nghìn kiếp được hưởng những sự an vui luôn."  
  
Bấy giờ, Đức Thế Tôn liền nói kệ rằng:  
  
Ta xem Địa Tạng sức oai thần  
Kiếp số hằng sa khó tỏ trần,  
Thấy nghe một niệm chiêm ngưỡng lễ.  
Trời, người lợi ích sự không ngằn  

Hoặc Rồng, hoặc Thần cùng nam nữ  
Báo tận sẽ sa vào đường dữ,  
Chí tâm quy mạng Đại sĩ thân,  
Tuổi thọ thêm nhiều trừ tội dữ.  
Trẻ thơ chết mất mẹ cùng cha,  
Huynh đệ chị em kẻ ruột rà,  
Lớn khôn nghĩ đến đều không biết,  
Nẻo dữ đường lành ở đâu là?  
Hoặc vẽ, hoặc tô Đại sĩ hình,  
Cảm thương chiêm lễ biệt chẳng đành,  
Hăm mốt ngày luôn niệm danh hiệu.  
Bồ Tát hiện thân đến bên mình,  
Chỉ rành quyến thuộc ở nơi nào,  
Dầu sa ác thú cũng ra mau,  
Nếu được không lui lòng kính ngưỡng.  
Thánh ký, Bồ Tát vuốt đầu trao.  

Bồ đề Vô thượng muốn tu hành,  
Mong ra ba cõi khỏi tử sanh,  
Người này đã phát lòng bi lớn  
Trước nên chiêm lễ Đại sĩ hình.  
Nghe tên, quy y Đấng trọn lành,  
Cúng dường cung kính phát lòng thành,  
Nghiệp chướng chẳng hề ngăn chướng đặng  
Bao nhiêu mong ước sớm viên thành.  

Có kẻ phát tâm tụng Kinh sách  
Muốn độ chúng sanh khỏi tai ách  
Dầu lập nguyện lớn chẳng nghĩ bàn  
Đọc rồi quên rồi luôn sót mất.  
Người này nghiệp chướng nó làm mê  
Học Đại thừa Kinh khó mọi bề,  
Y phục, ăn uống, các ngọa cụ,  
Cúng dường Địa Tạng với hương hoa.  
Dùng chén nước trong bày trước tượng,  
Cách một ngày đêm bưng lấy uống  
Sanh lòng ân trọng cữ ngũ tân  
Rượu, thịt, tà dâm cùng dối luống.  
Trong hăm mốt ngày chớ sát sanh,  
Chuyên lòng tưởng niệm Thượng Nhơn danh,  
Chiêm bao thấy rõ Tôn dung hiện  
Thức rồi, liền đặng trí khôn lanh.  
Đại thừa Kinh giáo nghe qua tai,  
Chính nhờ Đại sĩ oai thần lớn  
Thầm giúp người kia có huệ tài.  

Chúng sanh nghèo khổ lại ốm đau,  
Cửa nhà họa hoạn, người lìa nhau  
Ngủ mê mộng mị không an giấc,  
Cầu muốn hỏng hư chẳng được nào!  
Dốc lòng chiêm lễ Địa Tạng ngài,  
Bao nhiêu việc ác thảy tiêu ngay  
Nhẫn đến chiêm bao đều an cả,  
Quỷ Thần phò hộ, của dư xài.  

Muốn qua sông biển đến núi rừng,  
Cầm thú độc nguy, giặc đón đường,  
Ác Thần, ác Quỷ, mưa gió dữ  
Nhiều nỗi gian nan khốn không lường,  
Sắp sửa ra đi đối trước tượng  
Cúng dường kính lễ cùng chiêm ngưỡng  
Núi rừng biển cả có vào trong  
Ác tai tiêu sạch thường an sướng.  

Quán Âm lóng nghe Ta nói rõ  
Địa Tạng vô lượng oai thần đó,  
Trăm nghìn muôn kiếp thuật chẳng rồi,  
Rộng tuyên Đại sĩ đầy sức nọ!  

Như người nghe đến Địa Tạng danh,  
Thấy hình chiêm lễ hết lòng thành,  
Hương hoa, ăn uống, dâng y phục,  
Trăm nghìn báo đẹp hưởng điều lành.  
  
Nếu hay đem công hồi pháp giới,  
Rốt ráo thành Phật, sanh tử khỏi,  
Quán Âm nên biết gắng tuyên bày,  
Truyền khắp hằng sa nhiều nước cõi!  
