# Phẩm hồi hướng {- #pham-hoi-huong}
  
## Ma Ha Bát Nhã Ba La Mật Đa Tâm Kinh {- #bat-nha-tam-kinh}
  
Quán Tự Tại Bồ Tát hành thâm Bát nhã Ba la mật đa thời chiếu kiến ngũ uẩn giai không, độ nhứt thiết khổ ách.  
  
Xá Lợi Tử! Sắc bất dị không, không bất dị sắc, sắc tức thị không, không tức thị sắc; thọ, tưởng, hành, thức, diệt phục như thị.  
  
Xá Lợi Tử! Thị chư pháp không tướng: bất sanh, bất diệt, bất cấu, bất tịnh, bất tăng, bất giảm. Thị cố, không trung vô sắc, vô thọ, tưởng, hành, thức; vô nhãn, nhĩ, tỹ, thiệt, thân, ý; cô sắc, thinh, hương, vị, xúc, pháp; vô nhãn giới nãi chí vô ý thức giới, vô vô minh, diệc vô vô minh tận, nãi chí vô lão tử, diệc vô lão tử tận; vô khổ, tập, diệt, đạo, vô trí diệc vô đắc.  
  
Dĩ vô sở đắc cố, Bồ đề tát đỏa y Bát nhã Ba la mật đa cố, tâm vô quái ngại, vô quái ngại cố, vô hữu khủng bố, viễn ly điên đảo mộng tưởng, cứu cánh Niết Bàn.  
  
Tam thế chư Phật y Bát nhã Ba la mật đa cố, đắc A nậu đa la Tam miệu tam Bồ đề. Cố tri Bát nhã Ba la mật đa thị đại thần chú, thị đại minh chú, thị vô thượng chú, thị vô đẳng đẳng chú, năng trừ nhứt thiết khổ, chơn thiệt bất hư. Cố thuyết Bát nhã Ba la mật đa chú. Tức thuyết chú viết: Yết đế, yết đế, ba la yết đế, ba la tăng yết đế, Bồ đề tát bà ha.  
  
## Bạt Nhứt Thiết Nghiệp Chướng Căn Bổn Đắc Sanh Tịnh Độ Đà Ra Ni  {- #bat-nhut-thiet-nghiep-chuong}
  
Nam mô A di đa bà dạ. Đa tha già đa dạ. Đa điệt dạ tha. A di rị đô bà tỳ. A di rị đa tất đam bà tỳ, a di rị đa, tỳ can lan đế. A di rị đa, tỳ can lan đa. Dà di nị, già dà na. Chỉ đa ca lệ, Ta bà ha. *(3 lần)*  
  
A Di Đà Phật thân kim sắc,  
Tướng hảo quang minh vô đẳng luân,  
Bạch hào uyển chuyển ngũ Tu Di,  
Hám mục trừng thanh tứ đại hải,  
Quang trung hóa Phật vô số ức,  
Hóa Bồ Tát chúng diệc vô biên,  
Tứ thập bát nguyện độ chúng sanh,  
Cửu phẩm hàm linh đăng bỉ ngạn.  
  
Nam mô Tây Phương Cực Lạc Thế giới, Đại từ, Đại bi A Di Đà Phật.  
  
Nam mô A Di Đà Phật. *(108 lần)*  
Nam mô Quán Thế Âm Bồ Tát. *(10 lần)*  
Nam mô Đại Thế Chí Bồ Tát. *(10 lần)*  
Nam mô Địa Tạng Vương Bồ Tát. *(10 lần)*  
Nam mô Thanh Tịnh Đại Hải Chúng Bồ Tát. *(10 lần)*  
  
  
## Sám thập phương  {- #sam-thap-phuong}
  
Thập phương tam thế Phật  
A Di Đà đệ nhứt,  
Cửu phẩm độ chúng sanh,  
Oai đức vô cùng cực,  
Ngã kim đại quy y.  
Sám hối tam nghiệp tội,  
Phàm hữu chư phước thiện,  
Chí tâm dụng hồi hướng.  
Nguyện đồng niệm Phật nhơn  
Cảm ứng tùy thời hiện,  
Lâm chung Tây phương cảnh,  
Phân minh tại mục tiền,  
Kiến văn giai tinh tấn,  
Đồng sanh Cực Lạc quốc,  
Kiến Phật liễu sanh tử,  
Như Phật độ nhứt thiết.  
Vô biên phiền não đoạn  
Vô lượng pháp môn tu  
Thệ nguyện độ chúng sanh  
Tổng giai thành Phật đạo.  
Hư không hữu tận,  
Ngã nguyện vô cùng,  
Tình dữ vô tình,  
Đồng viên chủng trí.  
  
  
Nhứt giả lễ kính chư Phật,  
Nhị giả xưng tán Như Lai,  
Tam giả quảng tu cúng dường,  
Tứ giả sám hối nghiệp chướng,  
Ngũ giả tùy hỷ công đức,  
Lục giả thỉnh chuyển pháp luân,  
Thất giả thỉnh Phật trụ thế,  
Bát giả thường tùy Phật học,  
Cửu giả hằng thuận chúng sanh,  
Thập giả phổ giai hồi hướng.  
  
## Sám mười phương {- #sam-muoi-phuong}
  
Mười phương chư Phật ba đời,  
Di Đà bậc nhứt chẳng rời quần sanh,  
Sen vàng chín phẩm sẵn dành,  
Oai linh đức cả đã thành vô biên!  
Nay con dâng tấm lòng thiền  
Quy y với Phật, sám liền tội căn,  
Phước lành con có chi chăng,  
Ít nhiều quyết cũng nguyện rằng về Tây.  
Nguyện cùng với bạn tu đây,  
Tùy thời cảm ứng hiện ngay điềm lành,  
Biết giờ, biết khắc rõ rành,  
Lâm chung tạn mặt cảnh lành Tây phương.  
Thấy nghe chánh niệm hơn thường,  
Vãng sanh Lạc quốc đồng nương hoa vàng,  
Hoa nở thấy Phật rõ ràng,  
Thoát vòng sanh tử, độ an muôn loài.  
Phiền não vô tận, thệ dứt trừ,  
Pháp môn tu học, chẳng còn dư,  
Chúng sanh nguyện độ, bờ kia đến,  
Phật đạo cùng nhau chứng trí như.  
Hư không cõi nọ dẫu cùng,  
Nguyện con còn mãi chẳng cùng chẳng thiên.  
Không tình cùng có đồng nguyền,  
Trí mầu của Phật đồng viên đồng thành.  
  
  
## Sám Phổ Hiền {- #sam-pho-hien}
  
Nay con lại nguyện tu hành,  
Phổ Hiền nguyện lớn sẵn dành mười môn:  
Một, là nguyện lạy Thế Tôn,  
Hiện thân trước Phật hết lòng kính tin.  
Hai, khen Phật đức rộng thinh,  
Lời hay, tiếng tốt tận tình ngợi ca.  
Ba, thời sắm đủ hương hoa,  
Tràng phan bảo cái dâng ra cúng dường.  
Bốn, vì mê chấp lầm đường  
Tham sân nghiệp chướng con thường sám luôn.  
Năm, suy công đức vàn muôn  
Của phàm của Thánh con đồng vui ưa.  
Sáu, khi Phật chứng Thượng thừa  
Pháp mầu con thỉnh đã vừa truyền trao.  
Bảy, lòng chẳng chút lãng xao,  
Cầu xin chư Phật chớ vào Vô dư!  
Tám, thường tu học Đại thừa  
Bao giờ bằng Phật mới vừa lòng con.  
Chín, thề chẳng dám mõi mòn,  
Dắt dìu muôn loại đều tròn Pháp thân,  
Mười, đem tất cả công huân,  
Mọi loài cùng hưởng, khắp trần cùng vui.  
Mười điều nguyện lớn nguyện rồi,  
Nguyện về Cực Lạc nguyện ngồi tòa sen.  
  
  
## Hồi hướng {- #hoi-huong}
  
Phúng Kinh công đức thù thắng hạnh  
Vô biên thắng phước giai hồi hướng  
Phổ nguyện pháp giới chư chúng sanh  
Tốc vãng vô lượng quang Phật sát  
Nguyện tiêu tam chướng trừ phiền não  
Nguyện đắc trí huệ chơn minh liễu,  
Phổ nguyện tội chướng tất tiêu trừ,  
Thế thế thường hành Bồ Tát đạo,  
Nguyện sanh Tây phương Tịnh độ trung,  
Cửu phẩm liên hoa vi phụ mẫu,  
Hoa khai kiến Phật ngộ Vô sanh,  
Bất thối Bồ Tát vi bạn lữ.  
  
Nguyện dĩ thử công đức  
Phổ cập ư nhứt thiết  
Ngã đẳng dữ chúng sanh  
Giai cộng thành Phật đạo.  
  
  
## Phục nguyện {- #phuc-nguyen}
  
A Di Đà Phật thường lai hộ trì, linh ngã thiện căn, hiện tiền tăng tấn, bất thất tịnh nhơn. Lâm mạng chung thời, thân tâm chánh niệm, thị thính phân minh, diện phụng Di Đà, dữ chư Thánh chúng, thủ chấp kim đài, lai nghinh tiếp ngã, nhứt sát na khoảnh, sanh tại Phật tiền, cụ Bồ Tát đạo, quảng độ chúng sanh, đồng thành chủng trí.  
  
Nam mô Tây Phương Cực Lạc Thế giới, Đại từ Đại bi A Di Đà Phật. *(1 lạy)*  
  
Nam mô Tây Phương Cực Lạc Thế giới, Đại Bi Quán Thế Âm Bồ Tát, Đại Thế Chí Bồ Tát, Thanh Tịnh Đại Hải Chúng Bồ Tát. *(1 lạy)*  
  
Nam mô Tây Phương Cực Lạc Thế giới, Liên Trì Hải Hội Phật, Bồ Tát, nhứt thiết Hiền Thánh chúng chư Thượng Thiện Nhơn. *(1 lạy)*  
  
## Tam tự quy y {- #tam-tu-quy-y}
  
Tự quy y Phật, đương nguyện chúng sanh, thể giải Đại đạo, phát Vô thượng tâm. *(1 lạy)*  
  
Tự quy y Pháp, đương nguyện chúng sanh, thâm nhập Kinh tạng trí huệ như hải. *(1 lạy)*  
  
Tự quy y Tăng, đương nguyện chúng sanh, thống lý Đại chúng nhứt thiết vô ngại. *(1 lạy)*  
